"""Script generated by ansys-mapdl-core version 0.68.3"""

from ansys.mapdl.core import launch_mapdl
mapdl = launch_mapdl(loglevel="WARNING", print_com=True, check_parameter_names=False)

mapdl.clear()
mapdl.prep7()


# define arguments (useful for creating function)
mapdl.run("e=2e5")  # E
mapdl.run("nu=0.3")  # poissons ratio
mapdl.run("inner_radius= 175")
mapdl.run("outer_radius= 200")
mapdl.run("pressure=100")  # internal pressure
mapdl.run("element_size =1.4")  # element size


# Execute below lines within a function to execute in a loop
mapdl.et(1, 182, "", "", 2)

mapdl.pcirc("inner_radius", "outer_radius", 0, 90)
mapdl.cm("pipe_profile", "area")
mapdl.mp("ex", 1, "e")
mapdl.mp("prxy", 1, "nu")


mapdl.aesize("all", "element_size")
mapdl.mshape(0, "2D")
mapdl.mshkey(1)
mapdl.cmsel("s", "pipe_profile")
mapdl.amesh("all")


mapdl.nsel("s", "loc", "x")
mapdl.cm("x_fixed", "nodes")
mapdl.nsel("s", "loc", "y")
mapdl.cm("y_fixed", "node")

mapdl.lsel("s", "radius", "", "inner_radius")
mapdl.cm("pressure_edge", "line")
mapdl.allsel("all", "all")

mapdl.slashsolu()
mapdl.antype("static")
mapdl.d("x_fixed", "ux")
mapdl.d("y_fixed", "uy")

mapdl.csys(1)
mapdl.sfl("pressure_edge", "pres", "pressure")
mapdl.allsel("all", "all")
mapdl.solve()
mapdl.finish()

mapdl.post1()
mapdl.set(1, 1)
mapdl.plnsol("s", "eqv")

mapdl.exit()